name: Test and Lint

on:
  push:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run lint
        run: |
          make lint
        env:
          GO111MODULE: on
      - name: Run tests
        run: |
          make test
        env:
          GO111MODULE: on
      # Uncomment below action and enable coverage support
      # - uses: codecov/codecov-action@v1.0.2
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }} 
      #     file: ./src/coverage.txt #optional
